version: '2.4'
services:
  tppui:
    image: nginx:1.19
    volumes:
      - ./frontend/:/usr/share/nginx/html:ro
    ports:
      - "8081:80"
  tpp-backend:
    build: './backend'
    ports:
      - "8001:8000"